export class Cv{
    _id?:Object
    user_id?:Object
    types?:string
    name?:string
    prenom?:string
    email?:string
    phone?:number
    address?:string
    profil?:string
    poste?:string
    date_1?:Date
    date_2?:Date
    description?:string
    diplome?:string
    date_dip?:number
    competence?:string
    languages?:string
}